version: "3.9"

services:
  django-api:
    build:
      context: ./backend_django
      dockerfile: Dockerfile.dev

    volumes:
      - ./backend_django/db.sqlite3:/api/db.sqlite3

    ports:
      - "8000:8000"
