# Generated by Django 3.1.4 on 2020-12-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ancho', models.IntegerField(verbose_name='Ancho (cm)')),
                ('alto', models.IntegerField(verbose_name='Alto (cm)')),
                ('creado', models.DateField(verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ancho', models.IntegerField(verbose_name='Ancho (cm)')),
                ('alto', models.IntegerField(verbose_name='Alto (cm)')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TamañoCuadro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuadros.cuadro')),
                ('tamaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuadros.tamaño')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cuadros')),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuadros.cuadro')),
            ],
        ),
        migrations.AddField(
            model_name='cuadro',
            name='tamaños',
            field=models.ManyToManyField(through='cuadros.TamañoCuadro', to='cuadros.Tamaño'),
        ),
    ]
