# Generated by Django 3.1.4 on 2020-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadros', '0002_auto_20201209_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='creado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
