# Generated by Django 3.1.4 on 2020-12-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuadros', '0004_auto_20201209_1707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tamañocuadro',
            unique_together={('cuadro', 'tamaño')},
        ),
    ]
