# Generated by Django 3.1.4 on 2020-12-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadros', '0005_auto_20201209_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagen',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cuadro',
            name='alto',
            field=models.IntegerField(verbose_name='Alto (Original) [cm]'),
        ),
        migrations.AlterField(
            model_name='cuadro',
            name='ancho',
            field=models.IntegerField(verbose_name='Ancho (Original) [cm]'),
        ),
        migrations.AlterField(
            model_name='tamaño',
            name='alto',
            field=models.IntegerField(verbose_name='Alto [cm]'),
        ),
        migrations.AlterField(
            model_name='tamaño',
            name='ancho',
            field=models.IntegerField(verbose_name='Ancho [cm]'),
        ),
        migrations.AlterField(
            model_name='tamañocuadro',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio (sobreescribir)'),
        ),
    ]
