# Generated by Django 3.1.4 on 2020-12-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadros', '0006_auto_20201209_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamañocuadro',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
