# Generated by Django 3.1.4 on 2020-12-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuadros', '0008_auto_20201209_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuadro',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AddField(
            model_name='cuadro',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='cuadro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cuadros.cuadro'),
        ),
        migrations.AlterField(
            model_name='tamaño',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio [$]'),
        ),
        migrations.AlterField(
            model_name='tamañocuadro',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio (sobreescribir) [$]'),
        ),
    ]
