# Generated by Django 3.1.4 on 2020-12-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadros', '0010_auto_20201215_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='tamaños',
            field=models.ManyToManyField(through='cuadros.TamañoCuadro', to='cuadros.Tamaño', verbose_name='cuadros'),
        ),
    ]
