# Generated by Django 3.1.4 on 2020-12-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadros', '0011_auto_20201215_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='tag',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ordering'),
        ),
    ]
